version: "3.8"

services:
  moonscape-smartcontract:
    build:
      context: .
    container_name: "moonscape-smartcontract"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app/
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file: 
      - ./.env
    cap_add:
      - IPC_LOCK
    links:
      - local-node
  local-node:
    build:
      context: ./ganache
    container_name: "local-node"
    ports:
      - 8545:8545
    networks:
      - net
    volumes:
      - type: bind
        source: ./ganache/ganache_with_accounts.sh
        target: /app/ganache_with_accounts.sh
    command: "bash ganache_with_accounts.sh"
networks:
  net:
